---
- hosts: all
  become: yes
  tasks:
   - name: Install webserver on Ubuntu
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Debian"

   - name: start the webserver on ubuntu
     service:
      name: apache2
      state: started 
     when: ansible_os_family == "Debian"

   - name: Install webserver on Redhat
     yum:
      name: httpd
      state: present
     when: ansible_os_family =="Redhat"

   - name: Start the web service on Redhat
     service:
      name: httpd
      state: started
     when: ansible_os_family =="Redhat" 