---
- hosts: webserver
  become: yes
  tasks:
   - name: Install webserver on Ubuntu
     apt:
      name: "{{installubuntu}}"
      state: present
     when: ansible_os_family == "Debian"

   - name: start the webserver on ubuntu
     service:
      name: "{{installubuntu}}"
      state: started 
     when: ansible_os_family == "Debian"

   